### ISSUE TITLE
[0042/Bug] Stash graphics and custom map problems

### ISSUE THREAD

**Issue by bloodyshade** [davoodinator/XADAIL#1]
Mod Version: 0042 (S mode)
Issue:
    1) Stash graphics is messed up: https://s32.postimg.org/qa6ivqmid/stash.png
    2) Both DGA and Eternal maps are pretty much devoid of NPCs, there's only a few in DGA(Stash, Ghost Blacksmith, Skill Respec, etc) and none in Eternal.

Comments: Upgrade from 0036 -> 0042
I tried removing all the user saves and starting a new character altogether, also tried reinstalling the mod after a complete wipe (removed the dail files from the mods folder, restored the vanilla files, steam game cache verification, etc).

The custom main campaign map seem to have the NPCs (I even see the omega npc in devil's crossing's gate).

**Comment by davoodinator** [comment]
both of those should be fixed now with hotfix2
