### ISSUE TITLE
Terror Knight - Soldier of Madness

### ISSUE THREAD

**Issue by Zareks** [davoodinator/XADAIL#12]
It seems the ultimate level of this that gives +1 to all skills doesn't like being shared very much. Every time someone walks out of or into the aura range it lag spikes badly.(my guess is it is trying to calculate the +1 to all skills on the fly and when it does it to someone with a lot of skills, we are looking at a lot of calculation.) Perhaps we can make the skill not an aura anymore? Or if there is a way to make the +1 to all skills only affect the user of the ability?

**Comment by Kathanious** [comment]
Pushed to Zenith thread for dev evaluation.

**Comment by davoodinator** [comment]
closed issue
