### ISSUE TITLE
Survival Mode issues with solutions

### ISSUE THREAD

**Issue by davoodinator** [davoodinator/XADAIL#14]
*(SURVIVAL MODE RELATED( think some dbr-files are referencing on missing dbr files. For example
    Code:
    \DAIL - Survival\database\records\proxies\ascend_1\pool_aetherial08.dbr
    has a reference to
    Code:
    survival/creatures/wavespawn/ascend_1/enemy_gazer02b.dbr
    , but as far as i can see, there is no enemy_gazer02b.dbr?!

**Comment by kriescher1234** [comment]
Added the missing files.
