### ISSUE TITLE
priest / grove keeper still borked

### ISSUE THREAD

**Issue by davoodinator** [davoodinator/XADAIL#19]
*"Priest" problems
    Still no offensive summons in Priest like there should be either, makes the pet bonuses it has useless by itself.
    update "priest" to be whatever is in the latest dawn of heroes update

**Comment by Kathanious** [comment]
Priest updated to 3.4 in my local and plays well...will be in next pull

**Comment by Kathanious** [comment]
Fixed in pull#58
