### ISSUE TITLE
general frost knight issues

### ISSUE THREAD

**Issue by davoodinator** [davoodinator/XADAIL#20]
*While Frost Knight is looking much better, it's still got broken parts.
    It looks like Frost Aura is not itself, but rather one of the old attack skills, including the modifiers.
    The second modifier has a tag not found error for the name as well, tagFKSkillName02C.
    Howling Wind is missing the graphic (description mentions a cone of cold) and bizarrely has poison damage.
    Path of Frost's built-in devotion skill has another tag not found error for the pet it summons, tagPetWraith.
    Hoarfrost modifier for Frost Blast says it increases the AoE, but has no radius stat to do so.
    Cold Steel reads as a WPS (and was before IIRC) but only has passive stats, including acid and poison damage, not to mention a cold to acid conversion.

**Comment by Kathanious** [comment]
Done. Will be in next push.
