### ISSUE TITLE
miscellaneous but easy to fix UI issues

### ISSUE THREAD

**Issue by davoodinator** [davoodinator/XADAIL#24]
*MISC UI
       *Illusionist and ArchNecro functional but missing all graphics
    *Cenobite class selection points to Fangshi
    *Fangshi tree titled Coronus
    *Square icons with round borders look like crap, Ranger, Fangshi, Arelquin, Priest's "Great Charm of Water" icon, Frost Knight's "Glaciacian" icon, Terror Knight "Blood Rage" "Lust for Carnage"
    *Engineer skills beyond T9? Missing 3 skill information.
    *Terror Knight tagSkillClassDescription13 missing

**Comment by Kathanious** [comment]
Fixed. Square icons with round borders is still on going but the major stuff is done. Illusionist and Arch necro were corrected with GQmerge.bat as you suggested like a week ago! Derp on me.

**Comment by Kathanious** [comment]
The current pull request does not include the GQmerge.bat post compile process. You'll want to run that before test playing.
