### ISSUE TITLE
Something I can't figure out or just plain don't have time / interest to do it, but agree that it is a problem or interesting feature to add

### ISSUE THREAD

**Issue by Kathanious** [davoodinator/XADAIL#25]
Figured I'd keep these together for now rather than filling Issues tab. Additional, issues of this nature
can be added via comment.

^Ceno releasing new class, Champion, and own artwork for Elementalist and Terror Knight
^script for DAIL gift icon assortment, playerclass01 complete as test, 100+ entries per mastery by hand :(
^add the lazy mod for people who want auto pickups of stuff - needs more research - I haven't checked it yet
^see additional file anm_problems.txt
^survival mode i can't seem to fix the god spawn issues and the random crashing. use at your own risk.
^add/test a pull script to put stuff back into my offline work dir when I merge something from the wild (if it ever happens) put a bunch of pauses before it runs to be sure it doesn't run by accident. and make it only work if run from the git dir itself.
^if you play multiplayer with other people, if other players aren't in a close vicinity when the (component vendor) npcs appear - it won't be visible to others once they get there, only to the first player
^remove voidcaller items - i'd need an actual list.  not interested in diffing this out right now. it will be a pain.  im expecting Crate to raise the mastery limit beyond 30 so it shouldn't matter later. also i have templated it up to 99 but only 51 will display
^update graphics and naming conventions on the skill components - this is column A in all of the spreadsheet tabs if someone wants to update it and pass it over i will take it spreadsheet name is "masteries yyyy mm dd.xlsm" under \DAIL\database\DAIL\
^reverse spear models
^level75+ epics are not RNG properly? or whats the deal?
    ^fiddle with loot tables - are there duplicate entries? need magic script to check this.
    ^don't have time for this
^Discord Days: I wanted to propose that you add a new craftable to the game if possible! Aether Clusters!
^My game keeps crashing the moment Loghorrean attacks me, tried 3 times and on the third walked in slowly, stood there and when his projectiles hit me I crashed right away, on DAIL48 atm.
^add ground cleaner for survival mode
^camera acting weird. please read this http://steamcommunity.com/app/219990/discussions/1/357286663687417334/?tscn=1470506321
^IF YOUR READING THIS I CANT GET THE LAST THREE ULTIMATE SKILLS WORKING ON ENGINEER EVERYTHING IS LINKED RIGHT.  is it another arbitrary limit on the engine??? ! 
^look into merging the dawn of heroes music files into ambient mix
^Door to survival arena in multiplayer can not be gone through except by host others get stuck on invisible wall. This was on version 0050

**Comment by davoodinator** [comment]
should make these individual entries into the issues thread. then we can tag them as "nice to have but hard to figure out"

**Comment by davoodinator** [comment]
its ok to have them "clogging up" the issues section because we can filter

also alot of these are brought up frequently. so giving people a way to respond to individual items might help resolve them more effectively.

**Comment by davoodinator** [comment]
lets use "help wanted" for nice to have stuff

**Comment by davoodinator** [comment]
i added each of the ones that werne't already handled. as individual "help wanted" entries.
