### ISSUE TITLE
remove voidcaller items

### ISSUE THREAD

**Issue by davoodinator** [davoodinator/XADAIL#35]
^remove voidcaller items - i'd need an actual list. not interested in diffing this out right now. it will be a pain. im expecting Crate to raise the mastery limit beyond 30 so it shouldn't matter later. also i have templated it up to 99 but only 51 will display

**Comment by Kathanious** [comment]
Voidcaller mastery merged in DAIL 2.0, pull #67. Items can stay. Whether they are in loot tables is another question.
