### ISSUE TITLE
add lazy mod for auto pickups

### ISSUE THREAD

**Issue by davoodinator** [davoodinator/XADAIL#40]
^add the lazy mod for people who want auto pickups of stuff - needs more research - I haven't checked it yet

**Comment by Kathanious** [comment]
Compared some files...a few fields are changed in the creatures dbrs. Would need to go through each by hand to preserve some fields. Source info not provided for main.lua so unable to compare. Looks like the files are already in DAIL directories, it's just not integrated yet.

**Comment by Kathanious** [comment]
Couldn't get it to work, crashes DAIL. Even made back-ups of working then did complete over-write with autoloot files...still crashed.
