### ISSUE TITLE
REPORTING BUG IN DEMOLIST ^^

### ISSUE THREAD

**Issue by Duz1NN** [davoodinator/XADAIL#51]
Hey Davoo ,  i dont know if this cube appeared only for me and do not know what happened. Because I only use DAIL MOD in GD, i dont have other mod installed. 
But no problems, just like to report this bug that appeared to me. 
I go attach the image :P please check.
![demo](https://cloud.githubusercontent.com/assets/22010995/18331393/ed77d024-7534-11e6-811d-e7ce3480d19b.jpg)

**Comment by Kathanious** [comment]
The only mod to base classes is mastery investment post 50. His picture is
showing a double transmuter on that skill. A three-way connector doesn't
exist in vanilla.

**Comment by Duz1NN** [comment]
Yes, I noticed it, but I do not know what it is, I have just installed the DAIL MOD, the version I'm using is the latest 054CFI

**Comment by Kathanious** [comment]
I double checked base class database, it's possible cornucopia has
something stashed somewhere else. Try verifying game files if you are on
steam.

**Comment by Kathanious** [comment]
This was a change in Vanilla. If you are still missing that connector icon, try verifying game files.
