### ISSUE TITLE
cant level up (seems fixed for me thanks to the update)

### ISSUE THREAD

**Issue by TheDerpest** [davoodinator/XADAIL#73]
when i create a new char it says max level at 1, old char are now stuck at there level aswell, im on the 18-09-2016 version 0055CFI1

i tested some more its only in the dail-world001.map , the other 2 are working normal

**Comment by TheDerpest** [comment]
![pic](https://cloud.githubusercontent.com/assets/22274327/18615463/168f0d62-7da8-11e6-8ce6-39a5ae6054b5.jpg)

**Comment by BallsPara** [comment]
Same issue here as well mate :(
Tried to have a play around to see if I could copy some files around to get it working - No luck though.
It does appear to save your character though.

I leveled up a couple of times in the RIFT one but then still doesnt let you level past that level when you load back in.
Will let you know if I get mine working mate

**Comment by jbgamer** [comment]
I am also having the same issue, I can level in the other two custom maps but in the regular world my character is at max level

**Comment by TheDerpest** [comment]
the problem is somewhere in the dail.arz in the mods-dail-database but cant seem to figure it out hope this somewhat helps

**Comment by Kamui12** [comment]
I also have the same problem since the update 55

**Comment by Kamui12** [comment]
Just for completed : i have selectionned option B for installation and test X and i'ts correct level up
(sorry for my english)

**Comment by peregrine111** [comment]
And here I thought 54 was the most messed up version to date. Now we're stuck at level 1 in v55. Oh well, gonna try reinstalling mode other than B to see if it helps, but I'm not too optimistic..

**Comment by peregrine111** [comment]
Tried reinstaling with X mode - game crashes to desktop after hitting START button. Wonderful.

**Comment by peregrine111** [comment]
Tried leveling up the Voidcaller in X's Survival mode (aka the only thing that I managed to launch), but the game crashed after I used voidcaller's charge skill on Warden Krieg in 10th round..

**Comment by john45d** [comment]
Seems to be a problem with the (S) install option, i did (ASX) and i can lvl on the first world mod.

**Comment by KALLIAK** [comment]
Same problem. B option. v0055CFI1

**Comment by KALLIAK** [comment]
TheDerpest, how do you fix it? Cant level up on last 55HF2 version...
