### ISSUE TITLE
Build 55 so far

### ISSUE THREAD

**Issue by peregrine111** [davoodinator/XADAIL#77]
1) Option B main game mode gets stuck on level 1 as the max character level

2) Option X main game mode gets CTD on loading screen after hitting start button

FIXED in local working -3) Ranger mastery is COMPLETELY gone, I mean, there's just a bunch of empty bubbles with large red 'X'es beneath them

4) Voidcaller's charge (called some Mutilation or whatever, don't remember the name) skill sometimes crashes the game (not to mention it's unusable at best, as it's animation is so long you can get hit even twice after getting to target while you swing, and I'm not even talking about it's terribly weak damage per second)

Mastery DEV issue, not DAIL- 5) Dunno who put together the Demon Hunter mastery, but it's pure blarghf! Seriously, if you want to go with the scheme, then do so within 1-2 damage types, not like 8. Seriously, every skill does different type of damage. Are we supposed to stash +ALL damage items from 10 playthroughs to level up a Demon Hunter, or be content with doing like zero damage?

Mastery DEV issue, not DAIL - 6) why are people putting TERRIFY or KNOCKDOWN effect into abilities that are not panic buttons (especially melee abilities on a level of default attack modifier)? Do they enjoy chasing mobs with 5-20% HP left across whole maps?

**Comment by Kathanious** [comment]
9/26 20:30, updated list

**Comment by Kathanious** [comment]
Version 56 coming soon. Reevaluate this bug after version goes live.
