### ISSUE TITLE
Build 55HF2 Frost Knight > Ice Revenant

### ISSUE THREAD

**Issue by Wojmistrz** [davoodinator/XADAIL#82]
Hello Dear friends, i am playing on DAIL SX mode (Raid style hell yeah!) on world01 << ye default GD map and well as in the name of topic Frost Knight Ice Revenant is not working at all, i can summon him but he stand like dummy doing nothing (need to reverse this skill from my skill tree) :( can You fix this? Companion would help me alot there :) i will see if i encounter any new bugs (got Terror Knight as a secondary specialization) cool name tho Frostmare from combination of this two :dancer: 

Before You asking it is on CLEAN install of GD that already have DLC included (newest version of GD)

**Comment by Wojmistrz** [comment]
P.S: summon is not working on ALL modes (Main, Rift and Survival)

**Comment by Kathanious** [comment]
Version 56 coming soon. Previous pet fixes were reversed during out-of-sync issue. Fixed...again.
