### ISSUE TITLE
Engineer's turrets models are messed up. They show up as swords on the ground and produce no damage at all

### ISSUE THREAD

**Issue by AndreRulofs** [davoodinator/XADAIL#84]
The first engineer turrets are bugged

Installed over a fresh steam copy, no other mods.
Difficulty S atm, although X and others did not seem to work as well.
The turret shoots. The projectile appears before the kilt of the "sword" and than just dissapears.

**Comment by ghost** [comment]
Can confirm this
image of the sword: http://imgur.com/a/xHTNi
this for me was in the latest build : DAIL0055-FULL-HF2-11-0055CFI2
installed with option ng for the difficulty
no prevous installed mods (its the first one i have tried) 
the sword does turn and trys to shoot the ememies, a ball appears but seems to imediatly hit the terrain
over on reddit the developer of the engineer class said he looked at the code but couldnt see anything wrong (posted there first as i was unsure if it was a bug or an unfinished feature) 
link: https://www.reddit.com/r/Grimdawn/comments/54zthc/dail_mod_engineers_turret_bug/
EDIT:
i am using the steam version, but have turned cloud storage off so im using the save folder in the my documents folder, no idea if that helps or not lol

**Comment by Kathanious** [comment]
Turrets summon correctly in test play.  Version 56 coming soon. Reevaluate this bug after version goes live.

**Comment by ghost** [comment]
tried full reinstall of the game twice but still have the issue, is the test version already 56 or did you test on a 55 build? 
Will 56 hit nexus first or is it available somewhere else beforehand (keen to be able to play again)

**Comment by Kathanious** [comment]
I have a 56 stealth version up under dail/release. Points to my drop box.

**Comment by ghost** [comment]
Releases are showing as empty to me?

**Comment by AndreRulofs** [comment]
Could you please send a link to 56th release? I have no idea where to find it.

**Comment by Kathanious** [comment]
http://www.grimdawn.com/forums/showthread.php?t=46374&page=11

**Comment by AndreRulofs** [comment]
0056 Does not work. Install on a clean game. Windows 10. The same model as in 0055. I must add, in 0054, the version that I use, the turrets model is also messed up, however it doesn't effect their ability to damage. Their model becomes this: http://i.imgur.com/A1YDZ4I.png. The turret in versions 0055 and 0056 does do damage but at a very close range, a monster needs to stand directly on top of it which brings me to a conclusion that because of the sword being on the ground, the projectile collides with it upon spawning and does damage around it. 

Moreover, I play with a friend playing on 0055 while I play on 0054(he wants to play demon hunter, it somehow works with each other). He also sees swords instead of turrets(windows 7). I am a host, so while he sees swords, the turrets do shoot projectiles on his screen as well as on mine.

I hope it helps. In conclusion 0056 did not resolve the issue.

**Comment by Kathanious** [comment]
If you get the opportunity, test NG mode please.

**Comment by ghost** [comment]
installed 56 over 55, same bug
deleted the local version install on steam, re-installed then installed 56 
same bug
tried in single player as well as hosting multiplayer
Only tried ng difficulty, will try the others after work
also windows 10
(just seen your reply above ....yep that was ng mode(well ng setting in install))

edit: so version 54 is playable? (working turrets just bad model?) @AndreRulofs

**Comment by AndreRulofs** [comment]
Tried on S version than on NG. Does not work. The same bug still happens.

**Comment by ghost** [comment]
Not sure if this could be a factor or not but I do not own the dlc pack

**Comment by ghost** [comment]
installed build 54 and the turrets work, with the model AndreRulofs showed, the large tank with red tanks around it. wierd thing is it even rotates to shoot the bad guys.
@Kathanious can we get this issue re-opened as it is still an issue with build 55 and the beta of 56

**Comment by Kathanious** [comment]
56 has been released on nexus. Play test and feedback show it working. The
installer has been disabled so you will have to download the parts you want

**Comment by ghost** [comment]
@Kathanious ok i deleted my local content and reinstalled grim dawn fresh, downloaded the first file in the dail's new nexus entry (the 7z 600mb file located here http://www.nexusmods.com/grimdawn/mods/29/?tab=2&navtag=http%3A%2F%2Fwww.nexusmods.com%2Fgrimdawn%2Fajax%2Fmodfiles%2F%3Fid%3D29&pUp=1) 
extracted that to the mods folder using a program called 7zip http://www.7-zip.org/download.html (windows built in zip manager did not like the 7z file)
and although the tags dont display on my character in the main menu (to say he is an engineer) he works and more importantly so do the turrets! 
Thank you!
(added as much detail as i could to help anyone else that may stumble on this issue, personally hate it when i have the same issue as someone and find "solved it thanks" with no detail lol, pet peev)

**Comment by Kathanious** [comment]
Once the mod is loaded, the tag error is gone. Until then, the game doesn't
know what that class is. Dail no longer over writes game files. Enjoy!

**Comment by ghost** [comment]
@Kathanious i just went to grab it again (was going to try b difficulty) and link a mate to it for multiplayer and the link to build 56 no longer works, can not find it on mod nexus at all, was there a critical bug?

**Comment by Kathanious** [comment]
Pulled to get the nexus thing sorted out. Will have it back up this
weekend. If you both still have the 7z files, you can share those to get
multiplayer going.
